apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: persistence-rabbitmq-server-0
    namespace: rabbitmq
  hostPath:
    path: /mnt/data/rabbitmq
